### ISSUE TITLE
Features Request

### ISSUE THREAD

**Issue by ghost** [brunohbrito/JP-Project#2]
Hi,

Thank you building this project!
Could I ask if you can add more functionality examples like maybe project management system where a admin can add products and user (staff) can maintain the product example update product price :)

**Comment by brunohbrito** [comment]
Hi Nico!

Thanks for your interest! 

The main goal of project is to be an Identity Server 4 Admin. So I've no plans to add any kind of these features.

**Comment by NicoCG** [comment]
@brunohbrito Thanks just thought this project was the rebuild and maintained version of Equinox project would of been cool if it at least had the Customers part like in equinox project 👍 showing people how to add, edit and delete data 👍 

but I understand 
> The main goal of project is to be an Identity Server 4 Admin. So I've no plans to add any kind of these features.
