### ISSUE TITLE
Admin account for live demo

### ISSUE THREAD

**Issue by CalvinPangch** [brunohbrito/JP-Project#3]
could you please provide a Admin account in the demo site ? so i can had a quick look ? i created the new account but the account is normal usuer so i guess i do not had permision to view to the Admin UI. Thanks

**Comment by brunohbrito** [comment]
Hi @CalvinPangch 

With normal user you can see every details, but you cant change it.

Admin Ui site:
https://jpproject.azurewebsites.net/admin-ui/
